# Custom built Github Actions Workflow by Caitlin

# Workflow should: 
# 1. Create PM2 Instance on Self-hosted runner
# 2. Test out main deployment CI/CD Pipeline
# Done!


name: Initiate PM2 Instance for Backend Server

on:
  pull_request:
    branches:
      - 86-DOB-Validation-CiCD-Pipeline

  push: 
    branches: 
      - 86-DOB-Validation-CiCD-Pipeline

jobs:
  deploy:
    name: Initiate
    runs-on: self-hosted

    steps:  
    - name: Pull repo - Backend
      run:  |
            cd /var/www/IT-Project-COMP30022/Backend
            pm2 start 'npm start' --name Backend
            cd /var/log/cicd
            pm2 status > initiatepm2.log
